<?php
/**
 * Category view template
 *
 * @var $block \Rocket\Catalog\Block\Category\View
 */
$shoppingEndDates = $block->getShoppingEndDates();
?>
<?php if (count($shoppingEndDates)): ?>
    <?php
    $storeClosesDay = date('d', strtotime($shoppingEndDates['storeCloses']));
    $storeClosesMonth = date('F', strtotime($shoppingEndDates['storeCloses']));
    $estShippingDay = date('d', strtotime($shoppingEndDates['estShipping']));
    $estShippingMonth = date('F', strtotime($shoppingEndDates['estShipping']));
    ?>

    <div class="pull-lg-right">
        <div style="width: 80px;text-align: center;font-size: 10px;">Est. Shipping</div>
        <div style="width: 80px;text-align: center;font-size: 18px;background-color: #e9e9e9;">
            <?= $estShippingMonth ?>
        </div>
        <div style="width: 80px;height:75px;background-color: #303030;font-size: 50px;color: white; padding-top: 30px;text-align: center;">
            <?= $estShippingDay ?>
        </div>
    </div>
    <div class="pull-lg-right">
        <div style="width: 80px; clear: both;text-align: center;font-size: 10px;">Store Closes</div>
        <div style="width: 80px; clear: both;text-align: center;font-size: 18px;background-color: #e9e9e9;">
            <?= $storeClosesMonth ?>
        </div>
        <div style="width: 80px;height:75px;background-color: #e92c46;font-size: 50px;color: white; padding-top: 30px;text-align: center;">
            <?= $storeClosesDay ?>
        </div>
    </div>
<?php
endif;